### ISSUE TITLE
No 4.1.1 tag

### ISSUE THREAD

**Issue by fladi** [django-treebeard/django-treebeard#66]
The latest release on PyPi does not have a corresponding git tag.

**Comment by jrief** [comment]
fixed

**Comment by fladi** [comment]
I'm still not seeing the tag here. Maybe you forgot to push?

**Comment by jrief** [comment]
ups, I forgot to push.
